services:
  certbot:
    container_name: certbot
    build: .
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs_data:/data/letsencrypt
      - ./../nginx-conf:/etc/nginx/conf.d
    networks:
      - infra
    restart: always

networks:
  infra:
    external: true
