services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    env_file:
      - .env
    restart: always
    ports:
      - "${PGADMIN_EXTERNAL_PORT:-5050}:80"
    networks:
      - infra
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL:-admin@local.com}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - pgadmin-servers:/servers

  datahub:
    image: postgres:17.2
    container_name: datahub
    restart: always
    ports:
      - "${DATAHUB_EXTERNAL_PORT:-5432}:5432"
    networks:
      - infra
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-datahub}
    volumes:
      - datahub-data:/var/lib/postgresql/data
    depends_on:
      - pgadmin
    
volumes:
  pgadmin-data:
  pgadmin-servers:
  datahub-data:

networks:
  infra:
    external: true
