services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - /run:/run
      - /opt:/opt
      - ./nginx-conf:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - infra
    restart: always

networks:
  infra:
    external: true
