services:
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx
    environment:
      - CERTBOT_EMAIL
    env_file:
      - .env
    volumes:
      - /run:/run
      - /opt:/opt
      - nginx_secrets:/etc/letsencrypt   
      - ./nginx-conf:/etc/nginx/user_conf.d
    ports:
      - "80:80"
      - "443:443"
    networks:
      - infra
    restart: unless-stopped

networks:
  infra:
    external: true

volumes:
  nginx_secrets:
