services:
  flower:
    image: mher/flower:2.0
    container_name: flower
    restart: always
    ports:
      - ${FLOWER_EXTERNAL_PORT:-5555}:5555
    networks:
      - infra
    environment:
      FLOWER_BASIC_AUTH: ${FLOWER_BASIC_AUTH:-admin:admin}
    depends_on:
      - redis
      - nginx
    command: ['flower', '--broker=redis://redis:6379', '--port=5555']
  
networks:
  infra:
    external: true
