version: '3.7'

services:
  minio1:
    image: quay.io/minio/minio:RELEASE.2024-05-28T17-19-04Z
    container_name: minio1
    command: server --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - /data/minio:/data
    networks:
      - infra
    restart: always

networks:
  infra:
    external: true
